#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/openvpn /sbin

mkdir -p "$DESTDIR/etc/openvpn/client/initramfs"

cp -p /etc/openvpn/client/initramfs.conf "$DESTDIR/etc/openvpn/client/"
cp -p /etc/openvpn/client/initramfs/* "$DESTDIR/etc/openvpn/client/initramfs/"
